### ISSUE TITLE
Use function component

### ISSUE THREAD

**Issue by sm1th** [flq/test-of-xstate#1]
Hey there,

I found your tutorial via the xstate docs, and I really appreciate the guide and the code.

One thing I did while following your tutorial was use a function component instead of a class component. I came up with something that works, but I was wondering if you had any suggestions on how best to do this.

My code is here: https://codesandbox.io/s/hardcore-haze-jzu2r

Cheers!

**Comment by sm1th** [comment]
I looked at the xstate docs again and discovered `@xstate/react` (I'm an xstate noob, forgive me!)

So I've updated my codesandbox to use it. I think it looks good :)

**Comment by flq** [comment]
I’m happy it worked out, looks good 👍🏼
